### ISSUE TITLE
Convert to JSON Response

### ISSUE THREAD

**Issue by Technopathic** [willvincent/feeds#13]
Hello, is it possible to return the Feed data as JSON?
Like so?

```
public function getFeed()
{
    $url = Feeds::make('http://example.com/rss', true);

    $feedData = array(
      'title'     => $url->get_title(),
      'permalink' => $url->get_permalink(),
      'items'     => $url->get_items(),
    );

    return Response::json($feedData)->setCallback(Input::get('callback'));
}
```

This gives me the error:
The Response content must be a string or object implementing __toString(), "boolean" given.

**Comment by willvincent** [comment]
The default response would be json, so simply doing `return $feedData;` should get you json output. the callback would only be necessary if you were creating a jsonp response.
