### ISSUE TITLE
Documentation Requires Review

### ISSUE THREAD

**Issue by xitude** [willvincent/feeds#14]
Thanks for the plugin. Im still trying to get it working, some things in the documentation don't work in 5.\* or have changed.

``` php
return View::make('tickets.bus.index');
```

There exists a helper-function, view(), which is in the global namespace, and may be used to simplify the syntax:

``` php
return view('tickets.bus.index');
```

You can use compact to add the data to the view

``` php
$data = []
return view('tickets.bus.index', compact('data');
```

Just incase you didnt know :+1:

**Comment by xitude** [comment]
I got my controller down to if you want an example.

``` php
$feed = Facades\FeedsFacade::make('https://status.digitalocean.com/rss');
$items = collect($feed->get_items());

return view('status.digitalocean', compact('items'));
```

**Comment by willvincent** [comment]
If you'd like to submit a pull request with updated documentation addressing specific problems, feel free, but the only particulars you mentioned are not necessary changes. Yes, view() can be used instead of View::make() but it does not have to be. similarly with compact().
