### ISSUE TITLE
Allow config option for set_timeout

### ISSUE THREAD

**Issue by Corys8646** [willvincent/feeds#16]
I've got a few feeds where the site exposes a lot of feeds and hits the default 10 second timeout. Would it be possible to add a config option to override the default 10 seconds?

**Comment by barisbora** [comment]
hi, u can easly configure. 

`$feed = Feeds::make('http://blog.case.edu/news/feed.atom');`

`$feed` is simplepie object and support simplepie whole [API](http://simplepie.org/api/class-SimplePie.html)

for example:

`$feed->set_timeout( 60 );`

[set_timeout API](http://simplepie.org/api/source-class-SimplePie.html#757)

**Comment by gaodeng** [comment]
@barisbora @willvincent  call $feed->set_timeout( 60 )  after $feed = Feeds::make('http://blog.case.edu/news/feed.atom');  will not work as the request already sent.

**Comment by pierrocknroll** [comment]
@willvincent please reopen since the solution of @barisbora won't work
The $this->simplepie->set_timeout(1000);
must be done BEFORE $this->simplepie->init();


PS : See https://github.com/willvincent/feeds/pull/47
