### ISSUE TITLE
feed->get_category() returns me  alfanumeric chracters.

### ISSUE THREAD

**Issue by celiktolga** [willvincent/feeds#18]
When getting get_category() from feeds, it shows me a alfanumeric chracters like "e13747d84a99df5ffcf2a446a867"  
why is that? Why not the name?

**Comment by barisbora** [comment]
Can you submit feed source link?

**Comment by celiktolga** [comment]
http://hasscript.com/feed/qa.rss
or
http://www.sabah.com.tr/rss/ekonomi.xml
doest matter, ı cannot get proper category. Could you please help?

**Comment by barisbora** [comment]
There is nothing wrong. get_category() SimplePie_Category object so you receive object's CDATA characters. I believe it will solve the problem

``` PHP
$feed = Feeds::make( [ 'http://hasscript.com/feed/qa.rss', 'http://www.sabah.com.tr/rss/ekonomi.xml' ] );

$items = $feed->get_items();

foreach ( $items as $item ) {

        foreach ( $item->get_categories() as $category ) {

                echo $category->get_label();

         }

}
```

or in blade

``` PHP
@foreach ( $items as $item )

        @foreach ( $item->get_categories() as $category ) {

                {{ $category->get_label() }}

         @endforeach

@endforeach
```

**Comment by celiktolga** [comment]
It worked, thank you.
I used to try to get using only get_categories() , not with get_labels(),
I could not catch it before like that :+1:
