### ISSUE TITLE
After install not work

### ISSUE THREAD

**Issue by haegemon** [willvincent/feeds#2]
When I try to use Feeds I get exception
Class 'willvincent\Feeds\Facades\Feeds' not found

Laravel 5.0.1

**Comment by alvarisi** [comment]
yes i have the same issues.. @willvincent

**Comment by haegemon** [comment]
You might rename  class Feeds to FeedsFacade at  src/Facades/FeedsFacade.php

**Comment by willvincent** [comment]
I haven't had time to focus on anything laravel in several months... I wonder if things have changed since I released this, as it was working at that time. 

You all are welcome to submit pull requests.

**Comment by haegemon** [comment]
Pull request #3  solve this problem

**Comment by droplister** [comment]
I had this issue. It was working and then stopped working randomly. I just ran: composer update and it worked again. So, try that.

Edit: hmmm.... composer update will fix the issue for me, but if I then run composer dump-autoload I get the error again. Any thoughts?

**Comment by haegemon** [comment]
@familymedia Can you put error log and require block of composer.json?

**Comment by haegemon** [comment]
For proper work at composer should be

```
    "require": {
          "willvincent/feeds": "dev-master",
    },
```

**Comment by aalaap** [comment]
Even after requiring `dev-master`, and hitting `vendor:publish`, I still had to add the following two lines to `app/config.php`:

    'providers' => [
        // ...
        willvincent\Feeds\FeedsServiceProvider::class,
    ],

     'aliases' => [
        // ...
        'Feeds'    => willvincent\Feeds\Facades\FeedsFacade::class,
    ],
