### ISSUE TITLE
How get <img> tag in CDATA in description?

### ISSUE THREAD

**Issue by dkrasov** [willvincent/feeds#20]
Hi,

i'm trying to parse RSS2.0 feed with your package, but I cant get <img> in the description's CDATA.

It goes like this:
`<description><![CDATA[<img width="150" height="150" src="http://blog.foodstarz.com/wp-content/uploads/2016/09/RZ_UMSCHLAG_Sweetandsalty_final.jpeg-150x150.jpg" class="attachment-thumbnail size-thumbnail wp-post-image" alt="rz_umschlag_sweetandsalty_final-jpeg" style="display: block; margin-bottom: 5px; clear:both;" srcset="http://blog.foodstarz.com/wp-content/uploads/2016/09/RZ_UMSCHLAG_Sweetandsalty_final.jpeg-150x150.jpg 150w, http://blog.foodstarz.com/wp-content/uploads/2016/09/RZ_UMSCHLAG_Sweetandsalty_final.jpeg-235x235.jpg 235w" sizes="(max-width: 150px) 100vw, 150px" />Brinner: the latest food trend Breakfast for night owls and&#8230;]]></description>`

How can I get that <img> source?

**Comment by willvincent** [comment]
Perhaps you're not aware, but this is simply a wrapper around the simplepie library. It doesn't particularly do anything special, other than make it a little bit easier to add simplepie to a laravel project.

Maybe this will help: http://stackoverflow.com/questions/11581823/cdata-in-simplepie
