### ISSUE TITLE
Laravel 5.4 Bug. Call to undefined method Illuminate\Foundation\Application::share()

### ISSUE THREAD

**Issue by imsus** [willvincent/feeds#24]
Steps Reproducing the bug:

1. Start Fresh Installation Laravel 5.4
2. Install Package `composer require willvincent/feeds`
3. Add Providers to Config/App.php
4. Run PHP Artisan in console. [ERROR]

Error Message:
```bash
[Symfony\Component\Debug\Exception\FatalThrowableError]
Call to undefined method Illuminate\Foundation\Application::share()
```

What should happened:
`php artisan` will run normally

**Comment by AhmedFawzy** [comment]
share mothod removed from laravel 5.4 and I used singletone instead so just wait Will to accept my pull request 
check  https://github.com/willvincent/feeds/pull/26

**Comment by willvincent** [comment]
I just need to do some checks to verify the pull request won't break earlier versions, then I will merge.

@AhmedFawzy thanks for pinging me, I hadn't noticed that there were outstanding PRs. :)

**Comment by willvincent** [comment]
There were three identical PRs for this issue. Merged the first, all three people will receive credit. Thanks. New release shortly.
