### ISSUE TITLE
Separating Multiple Feeds

### ISSUE THREAD

**Issue by zulandar** [willvincent/feeds#29]
So I am attempting to separate the feeds (cnn, yahoo, etc.). I successfully have them separated but once I reach 3 feeds I start getting Undefined variables even though on a var_dump or print_r its showing up correctly.

Example controller

$feed2 = Feeds::make([
      'http://feeds.reuters.com/reuters/topNews?format=xml'
    ],5, true);
    $feed3 = Feeds::make([
      'http://rss.cnn.com/rss/cnn_us.rss'
    ],5, true);
    $feed4 = Feeds::make([
      'http://news.yahoo.com/rss/'
    ],5, true);

$data2 = array(
      'title2' => $feed2->get_title(),
      'permalink2' => $feed2->get_permalink(),
      'items2' => $feed2->get_items(),
    );

    $data3 = array(
      'title3' => $feed3->get_title(),
      'permalink3' => $feed3->get_permalink(),
      'items3' => $feed3->get_items(),
    );

return View('home.index', $data1, $data2, $data3);

// Blade information

<div role="tabpanel" class="tab-pane" id="reuters">
      @foreach($items2 as $item)
        <a href="{{ $item->get_permalink() }}">{{ $item->get_title() }}</a><br />
        <small>Posted on {{ $item->get_date('j F Y | g:i a') }}</small><br />
      @endforeach
    </div>
    <div role="tabpanel" class="tab-pane" id="cnn">
      @foreach($items3 as $item)
        <a href="{{ $item->get_permalink() }}">{{ $item->get_title() }}</a><br />
        <small>Posted on {{ $item->get_date('j F Y | g:i a') }}</small><br />
      @endforeach
    </div>

**Comment by willvincent** [comment]
I don't really have any idea what's going on here, and it shouldn't have anything to do with this package as it's simply a very small wrapper around simple pie.

But having said that, I'd probably use arrays instead of individual variables for each feed, and resulting parsed data.  Something like this:

```php
$feeds = [
  Feeds::make([ 'http://feeds.reuters.com/reuters/topNews?format=xml' ],5, true),
  Feeds::make([ 'http://rss.cnn.com/rss/cnn_us.rss' ],5, true),
  Feeds::make([ 'http://news.yahoo.com/rss/' ],5, true),
];

$data = [];
foreach ($feeds as $feed) {
  // Maybe include a check here that the feed didn't error out?
  $data[] = [
    'title'           => $feed->get_title(),
    'permalink' => $feed->get_permalink(),
    'items'        => $feed->get_items(), 
    // Maybe better to iterate through the items instead of just assigning them here?
  ];
}

return view('home.index', ['feeds' => $data]);
```

Template:
```php
@foreach($feeds as $feed)
<div>
<h4><a href="{{ $feed['permalink'] }}" target="_blank">{{ $feed['title'] }}</a></h4>
<ul>
  @foreach($feed['items'] as $item)
  <li>{{ $item->get_title() }}
    <span>Posted on {{ $item->get_date('j F Y | g:i a') }}</span>
  </li>
  @endforeach
</ul>
</div>
@endforeach
```

Truth be told, I'm not entirely sure that separating the items is necessary. I don't really use this package, and as I said, it's just a very thin wrapper around simplepie to make using simplepie inside laravel really trivial.

**Comment by milanchheda** [comment]
```php
$feeds = [
  Feeds::make([ 'http://feeds.reuters.com/reuters/topNews?format=xml' ],5, true),
  Feeds::make([ 'http://rss.cnn.com/rss/cnn_us.rss' ],5, true),
  Feeds::make([ 'http://news.yahoo.com/rss/' ],5, true),
];

$data = [];
foreach ($feeds as $feed) {
  // Maybe include a check here that the feed didn't error out?
  $data[] = [
    'title'           => $feed->get_title(),
    'permalink' => $feed->get_permalink(),
    'items'        => $feed->get_items(), 
    'date'         => $feed->get_date(), // HOW DO I GET THIS?
    // Maybe better to iterate through the items instead of just assigning them here?
  ];
}

return view('home.index', ['feeds' => $data]);
```

I am trying to get date in the $data[] but somehow that's not working. Would be great if you can help and direct me. 
I want ```     'date'         => $feed->get_date(), ``` inside the $data[].

**Comment by zulandar** [comment]
So, this is how I split the feeds successfully (Could never get more then 3). I am sure it could be written better but it works.
```PHP
$feed2 = Feeds::make([
      'http://feeds.reuters.com/reuters/topNews?format=xml'
    ],10, true);
    $feed3 = Feeds::make([
      'http://rss.cnn.com/rss/cnn_us.rss'
    ],10, true);
    $feed4 = Feeds::make([
      'http://news.yahoo.com/rss/'
    ],10, true);

$incrementArray = 0;

$data2 = array(
      'title2' => $feed2->get_title(),
      'permalink2' => $feed2->get_permalink(),
      'items2' => $feed2->get_items(),
    );

    //Put data into own Array.
    $reuters = array();

    $incrementArray = 0;

    foreach($data2['items2'] as $item)
    {
      $title = $item->get_title();
      $link = $item->get_permalink();
      $date = $item->get_date('j F Y | g:i a');

      $finalArray = array();

      $finalArray = array_add($finalArray, 'title' .$incrementArray, $title);
      $finalArray = array_add($finalArray, 'date' .$incrementArray, $date);
      $finalArray = array_add($finalArray, 'link' .$incrementArray, $link);

      array_push($reuters, $finalArray);

      $incrementArray ++;

    }

    $data3 = array(
      'title3' => $feed3->get_title(),
      'permalink3' => $feed3->get_permalink(),
      'items3' => $feed3->get_items(),
    );

    //Put data into own Array.
    $cnn = array();

    $incrementArray = 0;

    foreach($data3['items3'] as $item)
    {
      $title = $item->get_title();
      $link = $item->get_permalink();
      $date = $item->get_date('j F Y | g:i a');

      $finalArray = array();

      $finalArray = array_add($finalArray, 'title' .$incrementArray, $title);
      $finalArray = array_add($finalArray, 'date' .$incrementArray, $date);
      $finalArray = array_add($finalArray, 'link' .$incrementArray, $link);

      array_push($cnn, $finalArray);

      $incrementArray ++;

    }

    $data4 = array(
      'title4' => $feed4->get_title(),
      'permalink4' => $feed4->get_permalink(),
      'items4' => $feed4->get_items(),
    );

    //Put data into own Array.
    $yahoo = array();

    $incrementArray = 0;

    foreach($data4['items4'] as $item)
    {
      $title = $item->get_title();
      $link = $item->get_permalink();
      $date = $item->get_date('j F Y | g:i a');

      $finalArray = array();

      $finalArray = array_add($finalArray, 'title' .$incrementArray, $title);
      $finalArray = array_add($finalArray, 'date' .$incrementArray, $date);
      $finalArray = array_add($finalArray, 'link' .$incrementArray, $link);

      array_push($yahoo, $finalArray);

      $incrementArray ++;

    }

return View('home.index', compact('reuters', 'cnn', 'yahoo'));

```

**Comment by willvincent** [comment]
These are not issues with this package. As has been stated, this package is simply a small wrapper around simplepie to provide a laravel facade.  

Actual simplepie issues and questions should be directed to that project: https://github.com/simplepie/simplepie
