### ISSUE TITLE
Rss feed not working?

### ISSUE THREAD

**Issue by sebasjes** [willvincent/feeds#31]
Hey, I am working on a web application.
But when I use this url:
https://thetisgendt.eu/feed/
The rss reader is not working
When I use this url: 
http://feeds.feedburner.com/tweakers/mixed
It works and I get a array back.
Do you know why?
Greetings Sebas.

**Comment by willvincent** [comment]
No idea. This package is just a simple wrapper around simplepie, if simplepie isn't properly parsing a feed, an issue should be opened there
