### ISSUE TITLE
Passing in XML as opposed to URL

### ISSUE THREAD

**Issue by atmediauk** [willvincent/feeds#35]
Hello,

This package seems great but just had a question (or feature if its not available).

Is it possible to pass in an XML string instead of a URL?

The reason I ask is because I wanted to retrieve the XML from multiple feeds myself using Guzzles batching feature (https://guzzle3.readthedocs.io/batching/batching.html) and then pass it in to this package to work with.

Thanks for your help.

**Comment by willvincent** [comment]
No. 

This is a wrapper around [SimplePie](http://simplepie.org/), it expects URLs only as it uses simple pie's `set_feed_url()` method. I would suggest you instead just use simplepie directly if you need different behavior.

However, I'll point out that multiple feeds can be used with this already, so there's really not much reason to fetch them differently, IMHO.
