### ISSUE TITLE
Laravel package discovery not working.

### ISSUE THREAD

**Issue by koenhoeijmakers** [willvincent/feeds#38]
As the title says, the `php artisan package:discover` method is not working, this is because the changes to the `composer.json` in the `master` branch are not released yet.

Would be nice to see it released as the readme already says it should work, but it doesn't _yet_ :).

**Comment by chadidi** [comment]
Use the `dev-master `for the latest updates like that:
`"willvincent/feeds": "dev-master"`

**Comment by mattstauffer** [comment]
@willvincent Are you planning to publish this update?

**Comment by willvincent** [comment]
Hey guys, yup I'll publish it now.. Apologies, I've been pulled away from the laravel community for work lately.

**Comment by willvincent** [comment]
v1.1.3 published.

**Comment by mattstauffer** [comment]
@willvincent Thanks dude! <3

**Comment by willvincent** [comment]
Not problem. Thanks for the reminder ;)
