### ISSUE TITLE
update from 1.1.2 to 1.1.3

### ISSUE THREAD

**Issue by allotmentandy** [willvincent/feeds#39]
not sure if it is to do with the problems with packagist today, but i upgraded from 1.1.2 to 1.1.3 and got

Undefined index: ssl_check.disabled
in feedfactory.php

**Comment by peeto** [comment]
@allotmentandy add ssl_check.disabled to your config (see src/config/feeds.php)

**Comment by allotmentandy** [comment]
thanks so much, that fixed it :)

**Comment by asomervell** [comment]
PHP 7.1 seem to be still getting this error. Definitely set in config. This [obviously] works:

`
        if (isset($this->config['ssl_check.disabled']) && $this->config['ssl_check.disabled']) {
            $curloptions[CURLOPT_SSL_VERIFYHOST] = false;
            $curloptions[CURLOPT_SSL_VERIFYPEER] = false;
        }
`
