### ISSUE TITLE
When add to composer.json and composer update:  "Your requirements could not be resolved to an installable set of packages."

### ISSUE THREAD

**Issue by nitogel** [willvincent/feeds#4]
Problem 1
    - Installation request for willvincent/feeds 1.0.\* -> satisfiable by willvincent/feeds[1.0.1].
    - willvincent/feeds 1.0.1 requires simplepie/simplepie 1.3.\* -> no matching package found.

**Comment by willvincent** [comment]
I certainly can't understand why... There absolutely is a package matching that:
https://packagist.org/packages/simplepie/simplepie

Must be a composer issue.
