### ISSUE TITLE
set a Proxy

### ISSUE THREAD

**Issue by philippe-corleone** [willvincent/feeds#40]
How I can set a proxy? A proxy is easily set in cURL options. Problem is, the files where I changes this are in vendor directory. On release it will be lost. Can you fix this problem?

**Comment by willvincent** [comment]
I assume you're referring to these lines:

```
    $this->simplepie->set_curl_options([
        CURLOPT_SSL_VERIFYHOST => false,
        CURLOPT_SSL_VERIFYPEER => false
    ]);
```

Seems to me the proper solution would be to expose a curl_options array in the config file, and merge that in here in this code in the factory.

PRs are welcome.

**Comment by philippe-corleone** [comment]
The property for php is "CURLOPT_PROXY".
I don't know where are these lines located. I have never wrote a package for laravel before. I want help you, but I'am not quite sure what to do. 

I mean, a property in the config file is the right way I think, but the package and your class have to read this property. In addition, I think it is even better to set this proxy information over a method, because the proxy is not always needed.

You could set a default-proxy in the config file and on a feed object a method to set the default-proxy for the current object. On initialization from a feed object the proxy is not set.

Thanks for your quick answer.
Let me know what I can do.

**Comment by peeto** [comment]
@philippe-corleone  I'm currently working on a patch for this

**Comment by peeto** [comment]
@philippe-corleone Please review and test changes: https://github.com/peeto/feeds/commit/3a26a9b625f3aa9a588c111057c285f5035ae951
or
https://github.com/willvincent/feeds/pull/41

**Comment by philippe-corleone** [comment]
Okay, I will do that. I have an other problem with my application at the moment. I will test it directly after solving it.

**Comment by philippe-corleone** [comment]
Hello, I could solve my problem and wanted test your code.

But I get the error:

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package willvincent/feeds (locked at v1.1.3, required as dev-master) is satisfiable by willvincent/feeds[v1.1.3] but these conflict with your requirements or minimum-stability.
```
This is my composer.json:

```
{
"repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/peeto/feeds"
        }
    ],
    "require": {
        "php": ">=5.5.9",
        "laravel/framework": "5.2.*",
        "zizaco/entrust": "5.2.x-dev",
        "laravelcollective/html": "5.2.*",
        "doctrine/dbal": "^2.6",
        "willvincent/feeds": "dev-master"
    },
    "require-dev": {
        "fzaninotto/faker": "~1.4",
        "mockery/mockery": "0.9.*",
        "phpunit/phpunit": "~4.0",
        "symfony/css-selector": "2.8.*|3.0.*",
        "symfony/dom-crawler": "2.8.*|3.0.*",
        "laravel/homestead": "^6.2",
        "dompdf/dompdf": "^0.8.1",
        "laracasts/generators": "^1.1"
    },
}
```

I have never before integrated a github fork in a composer.json file and orientated myself on this [post](https://stackoverflow.com/questions/13498519/how-to-require-a-fork-with-composer).

btw:
A friend of mine told me it was the normal way to make a new branch named "bugfix", but your branch is the master. Did I misunderstand him? That's why I wrote "dev-master" in my composer.json file. In the example from the post it is also "bugfix" in use.

Thanks beforehand for your help.

**Comment by peeto** [comment]
I've now published this for testing:

replace:

"willvincent/feeds": "dev-master"


with:

"peeto/feeds": "dev-master"

**Comment by philippe-corleone** [comment]
okay, very nice. It works. But know all feeds that I will get from any sources have to use the proxy, isn't it?

**Comment by peeto** [comment]
Yes,

But that's what you would expect/require yes?

**Comment by philippe-corleone** [comment]
Yes. I think the best way is:

```
Feeds::make(string $source, int $count, bool $proxy = false)

true -> use proxy
false (default) -> do not use the proxy
```

In my case some rss content comes from the intranet and some comes from the internet behind the proxy. I think other companies and people also need this feature. The proxy is always the same, I think. Therefore it can sets in the config file.

**Comment by peeto** [comment]
@philippe-corleone Based on a conversation I had with @willvincent it has been changed so instead of individual settings for different proxy settings an array of CURL options must be provided instead.

This is so we can cater for future needs. Currently yours are simple eg: you don't need to authenticate with the proxy or talk to a SOCKS proxy.

Your request above has been fulfilled, you need something like:

$options['curl.options'] = [CURLOPT_PROXY => 'url'];

@willvincent based on the request above I've added a $options parameter to make() in case other (non CURL) options get requested in the future.

@philippe-corleone I've released a new beta to packagist (peeto/feeds) so you can test this.

@willvincent The latest commit has the correct namespace (willvincent/feeds) so you can pull the code without needing to change this.

**Comment by peeto** [comment]
@philippe-corleone The code I've committed shows how you could have resolved this without raising this issue but please test anyway.

**Comment by willvincent** [comment]
New release 1.1.4 includes @peeto's changes.
