### ISSUE TITLE
How to get other data values 

### ISSUE THREAD

**Issue by diadal** [willvincent/feeds#46]
"xml_lang" => ""
        "child" => array:1 [▼
          "" => array:8 [▼
            "title" => array:1 [▶]
            "link" => array:1 [▶]
            "description" => array:1 [▶]
            "guid" => array:1 [▶]
            "creDate" => array:1 [▶]
            "pubDate" => array:1 [▶]
            "auname" => array:1 [▶]
            "uri" => array:1 [▶]
          ]
        ]
       how do I get uri, and pubDate

**Comment by willvincent** [comment]
This package is really just a wrapper around simplepie, so you'll want to review the documentation there for this sort thing.

I _think_ you probably want the [get_item_tags](http://simplepie.org/api/class-SimplePie_Item.html#_get_item_tags) method, which looks to allow you to grab any arbitrary value from a feed item.. assuming there's not a more fitting option available for feed items already. I didn't see anything, but didn't really scour the docs either.
