### ISSUE TITLE
ErrorException: Undefined index: ssl_check.disabled in /vendor/willvincent/feeds/src/FeedsFactory.php:75

### ISSUE THREAD

**Issue by msliman** [willvincent/feeds#49]
Hi,

Kindly help, I got this error placed in the title.

**Comment by gautam-patadiya** [comment]
Getting same error

**Comment by koenhoeijmakers** [comment]
This has to do with a package update, you can solve it by republishing the config.

I'll make a PR to fix this in future versions.
