### ISSUE TITLE
How can we use get_image_url()?

### ISSUE THREAD

**Issue by asunciongiancarlo** [willvincent/feeds#5]
Please help How can we use get_image_url()?

**Comment by haegemon** [comment]
If you want get image of material you can either 
1) Get source and from source get image url

```
foreach ($feedData->get_items() as $item) {
    if ($source = $item->get_source()) {
        $image = source->get_image_url();
    }
}
```

2) Get content and parse it

```
foreach ($feedData->get_items() as $item) {
   $content = $item->get_content();
}
```

If you want image of feed

```
$feedData = \Feeds::make("some_alias");
$imageUrl = $feedData->get_image_url();
```

[Source](http://simplepie.org/wiki/reference/simplepie/get_image_url)

**Comment by asunciongiancarlo** [comment]
Thanks man it is now working, Good Job!

**Comment by gonzaz704** [comment]
Hi, 
Im trying to get image from news feed with what you posted above 
foreach ($feedData->get_items() as $item) {
   $content = $item->get_content();
}

But the Laravel error says "Call to undefined method SimplePie::get_content() in ...."  
So there is no get_content() method?. How did you solve it?
