### ISSUE TITLE
Class 'simplePie' not found In FeedsFactory.php line 39:                                   

### ISSUE THREAD

**Issue by kylescousin** [willvincent/feeds#54]
All of a sudden I'm getting this error.
FeedsFactory.php does not have an instantiation of that class with lowercase s.

$ composer dump-autoload

or any other cli command gives the error.

Script @php artisan package:discover handling the post-autoload-dump event returned with error code 1

**Comment by kylescousin** [comment]
Actually it's lowercased here: https://github.com/willvincent/feeds/blob/master/src/FeedsFactory.php

Should be use SimplePie and new SimplePie()

**Comment by koenhoeijmakers** [comment]
You can prevent this by setting this in your composer.json `"willvincent/feeds": "1.1.5"` until PR #55 is merged

**Comment by pierrocknroll** [comment]
"Full-time application breaker." : indeed :p

**Comment by koenhoeijmakers** [comment]
A man must live up to his name, but except for that, it shouldn't have been merged, it should have been checked before merge.
Given that mistakes are human haha
