### ISSUE TITLE
cURL cannor resolve host

### ISSUE THREAD

**Issue by AndreFabris** [willvincent/feeds#57]
Hi I am testing locally, and my host is
appsforce.back
  +error: "cURL error 6: Could not resolve host: appsforce.back%2Fmyblog%2F
It seems here:
  +feed_url: "http://appsforce.back%2Fmyblog%2F/?feed=atom#"
  +permanent_url: "http://appsforce.back%2Fmyblog%2F/?feed=atom#"

That this plugin adds http:// which will not work for my local testing

**Comment by willvincent** [comment]
This package doesn't alter your defined url at all. Sounds like maybe you have issue with the underlying simplepie library that this package wraps up as a laravel provider.

All we do is set the value you [pass in as your feed url](https://github.com/willvincent/feeds/blob/master/src/FeedsFactory.php#L41)
