### ISSUE TITLE
Limiting Number of Reponses

### ISSUE THREAD

**Issue by bendparker** [willvincent/feeds#59]
This is more of a quesiton than an issue, and I apologize if this is the wrong place to post.  However, I want to know, if I limit the amount of items to pull from feed--for instnace I limit to five--will it always return the five most recent?

**Comment by willvincent** [comment]
I suspect it probably will, but that is also most likely dependent on the feed being consumed too.. I would suggest checking with simplepie as this is just a wrapped around it.
