### ISSUE TITLE
updating simple pie useragent

### ISSUE THREAD

**Issue by naelsaid** [willvincent/feeds#62]
Hi,

I was wondering if there is a way to update simple pie user agent. I was looking into the code and config file but did not see that offered. Is it possible to add a user_agent parameter to the config file?

**Comment by msassa** [comment]
I have the same question. I'm trying to get a feed, and with the default useragent ("SimplePie/1.5.2 (Feed Parser; http://simplepie.org; Allow like Gecko) Build/20190829125805") I'm getting a 301 🤷‍♂️
If I hardcode the useragent as null, I get the feed.

**Comment by naelsaid** [comment]
@msassa 
I solved the problem of changing the user agent by setting 
```
/*
    |--------------------------------------------------------------------------
    | CURL Options
    |--------------------------------------------------------------------------
    |
    | Array of CURL options (see curl_setopt())
    | Set to null to disable
    |
     */
    'curl.options' => [
        CURLOPT_USERAGENT => 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.103 Safari/537.36',
    ],
```
in the feeds.php config file. I still think that there should be a configuration to set it using the set_useragent() simplepie function

**Comment by msassa** [comment]
Yes, I solved the same way. Thanks !
