### ISSUE TITLE
compatibility with Laravel-6

### ISSUE THREAD

**Issue by olivM** [willvincent/feeds#63]
Hi,

Is there any plan to update compatibility with Laravel-6 ?

( if not i'm willing to help )

thanks

**Comment by pushpanda** [comment]
Looking forward too,

thank in advance

**Comment by olivM** [comment]
this fork is working nicely with Laravel-6 : https://github.com/janeirikh/feeds

**Comment by willvincent** [comment]
Just merged a PR from @mohamedsabil83 that allows install with laravel 6.

I will be looking at more updates to this package soon, if any are actually necessary/relevant.
