### ISSUE TITLE
Support for laravel 7

### ISSUE THREAD

**Issue by nickvleeuwen** [willvincent/feeds#71]
Hello,

Im trying to upgrade one of my applications to Laravel 7, I can't  do this because this package doesn't support Laravel 7 yet and my application is dependent on this package.

Will this package support Laravel 7 in the near future?

**Comment by maxxscho** [comment]
Laravel 7 support would be great!!

**Comment by maxxscho** [comment]
A PR for Laravel-7 support is already there - see #72
