### ISSUE TITLE
How to import?

### ISSUE THREAD

**Issue by tcagkansokmen** [willvincent/feeds#73]
It gives Class 'willvincent\Feeds' not found
 error and doesnt work when I try use willvincent\Feeds;

why there's no example how to use it?

**Comment by iapparatus** [comment]
Try running this command: `composer require willvincent/feeds`to install the package.

**Comment by ricardoa-vega-stori** [comment]
If using Laravel, try this:

`php artisan vendor:publish --provider="willvincent\Feeds\FeedsServiceProvider"`

Then in web.php

```
use willvincent\Feeds\Facades\FeedsFacade;

Route::get('/feed', function() {
    $feeds = FeedsFacade::make('YOUR_XML_URL);
    dd($feeds);
});
```

**Comment by pschaub** [comment]
Just use `\Feeds` instead of `Feeds`. See https://github.com/willvincent/feeds/pull/74

**Comment by careerhub-source** [comment]
How can get example on how to use the package in laravel, I follow the step but nothing display in homepage
